/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import static java.lang.Float.parseFloat;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.sql.PooledConnection;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.pool.OracleConnectionPoolDataSource;
import view.Principal.FuncionariobyCPF;
import view.Principal.PagamentobyCPF;


/**
 *
 * @author jonas
 */
public class Adicionais extends javax.swing.JFrame {

    public Adicionais() {
        initComponents();
    }
    Principal pag = new Principal();
    
    
    
    
    
    public Adicionais(String CPF) throws SQLException {
        //this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        
        cpfLabel.setText(CPF);
        
        OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
        ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
        ds.setUser("folhapagamento");
        ds.setPassword("senha");
        PooledConnection pc = ds.getPooledConnection();
        Connection conn=pc.getConnection();
        
        
        
        Principal.FuncionariobyCPF f = pag.new FuncionariobyCPF();
        Principal.PagamentobyCPF f2 = pag.new PagamentobyCPF();
        ResultSet rs = null, rs2 = null;
        rs = f.find(CPF, conn);
        rs2 = f2.find(CPF, conn);
        try{
            if(rs.next()){
                nomeLabel.setText(rs.getString("NOME_F"));
            }
            if(rs2.next()){
                txtComissao.setText(rs2.getString("ADCOMISSAO_P"));
                txtPericulosidade.setText(rs2.getString("ADPERICULOSIDADE_P"));
                txtHoraExtra.setText(rs2.getString("HORASEXTRATRABALHADAS"));
                txtInsalubridade.setText(rs2.getString("ADINSALUBRIDADE_P"));
            }
            /*
            resultSetClose(rs);
            resultSetClose(rs2);
            */
            try {
      
                    conn.close();
                    Thread.sleep(500);
                }
                catch(Exception e) { }
        }catch(Exception ex){
        }
        
        this.setSize(1280, 720);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtComissao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        btnComissao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtInsalubridade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPericulosidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHoraExtra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPericulosidade = new javax.swing.JButton();
        btnInsalubridade = new javax.swing.JButton();
        btnHoraExtra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Comissão:");

        txtComissao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtComissao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComissaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CPF:");

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeLabel.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nome:");

        cpfLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpfLabel.setText("jLabel2");

        btnComissao.setText("Alterar");
        btnComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComissaoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Insalubridade");

        txtInsalubridade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtInsalubridade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInsalubridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsalubridadeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Periculosidade:");

        txtPericulosidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPericulosidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPericulosidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPericulosidadeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Hora Extra:");

        txtHoraExtra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHoraExtra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoraExtra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraExtraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Horas");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Reais");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Reais");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Reais");

        btnPericulosidade.setText("Alterar");
        btnPericulosidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPericulosidadeActionPerformed(evt);
            }
        });

        btnInsalubridade.setText("Alterar");
        btnInsalubridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsalubridadeActionPerformed(evt);
            }
        });

        btnHoraExtra.setText("Alterar");
        btnHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoraExtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtComissao)
                            .addComponent(txtInsalubridade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPericulosidade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHoraExtra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnComissao)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPericulosidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnInsalubridade, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnHoraExtra, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpfLabel))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(txtInsalubridade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPericulosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addComponent(txtHoraExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsalubridade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addComponent(btnPericulosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHoraExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComissaoActionPerformed
        // TODO add your handling code here:

        ResultSet rs = null;
        OraclePreparedStatement ps = null;
        Float comissao=parseFloat(txtComissao.getText()); 
        
        try{
            OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
            ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ds.setUser("folhapagamento");
            ds.setPassword("senha");
            PooledConnection pc = ds.getPooledConnection();
            Connection conn=pc.getConnection();
            
            String SQL = "UPDATE pagamento SET adcomissao_p = ? where FK_PK_CPF_F ='" + cpfLabel.getText() + "'";
            
            ps = (OraclePreparedStatement)conn.prepareStatement(SQL);
            ps.setFloat(1, comissao);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Dados Inseridos");
            
            pag.calcImpostos(cpfLabel.getText());
            
            /*connectionClose(conn);
            resultSetClose(rs);
            preparedStatmentClose(ps);
            */
            try {
                    ps.close();
                    conn.close();
                    Thread.sleep(500);
                }
                catch(Exception e) { }
        }catch(SQLException e){
            System.out.println("Error no sql "+e);
        } 
           
    }//GEN-LAST:event_btnComissaoActionPerformed

    private void txtComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComissaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtComissaoActionPerformed

    private void txtInsalubridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsalubridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsalubridadeActionPerformed

    private void txtPericulosidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPericulosidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPericulosidadeActionPerformed

    private void txtHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraExtraActionPerformed

    private void btnPericulosidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPericulosidadeActionPerformed
        ResultSet rs = null;
        OraclePreparedStatement ps = null;
        
        Float periculosidade=parseFloat(txtPericulosidade.getText());
        String SQL = "UPDATE pagamento SET ADPERICULOSIDADE_P = ? where FK_PK_CPF_F ='" + cpfLabel.getText() + "'";
        
        try{
            OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
            ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ds.setUser("folhapagamento");
            ds.setPassword("senha");
            PooledConnection pc = ds.getPooledConnection();
            Connection conn=pc.getConnection();
            
            ps = (OraclePreparedStatement)conn.prepareStatement(SQL);

            ps.setFloat(1, periculosidade);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Dados Inseridos");
            pag.calcImpostos(cpfLabel.getText());
            
             try {
                    ps.close();
                    conn.close();
                    Thread.sleep(500);
                }
                catch(Exception e) { }
        }catch(SQLException e){
            System.out.println("Error no sql "+e);
        } 
        
       
        
    }//GEN-LAST:event_btnPericulosidadeActionPerformed

    private void btnInsalubridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsalubridadeActionPerformed
        // TODO add your handling code here: 
        ResultSet rs = null;
        OraclePreparedStatement ps = null;
        
        Float insalubridade=parseFloat(txtInsalubridade.getText());
        String SQL = "UPDATE pagamento SET ADINSALUBRIDADE_P = ? where FK_PK_CPF_F ='" + cpfLabel.getText() + "'";
        
        try{
            OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
            ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ds.setUser("folhapagamento");
            ds.setPassword("senha");
            PooledConnection pc = ds.getPooledConnection();
            Connection conn=pc.getConnection();
            
            ps = (OraclePreparedStatement)conn.prepareStatement(SQL);
            
            ps.setFloat(1, insalubridade);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Dados Inseridos");
            
            pag.calcImpostos(cpfLabel.getText());
             try {
                    ps.close();
                    conn.close();
                    Thread.sleep(500);
                }
                catch(Exception e) { }
        }catch(SQLException e){
            System.out.println("Error no sql "+e);
        } 
        
    }//GEN-LAST:event_btnInsalubridadeActionPerformed

    private void btnHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoraExtraActionPerformed
        // TODO add your handling code here: 
        ResultSet rs = null;
        OraclePreparedStatement ps = null;

        Float horaextra=parseFloat(txtHoraExtra.getText());
        if(horaextra == null)
            horaextra = 0f;
        String SQL = "UPDATE pagamento SET HORASEXTRATRABALHADAS = ? where FK_PK_CPF_F ='" + cpfLabel.getText() + "'";
        
        try{
            OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
            ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ds.setUser("folhapagamento");
            ds.setPassword("senha");
            PooledConnection pc = ds.getPooledConnection();
            Connection conn=pc.getConnection();
            
            ps = (OraclePreparedStatement)conn.prepareStatement(SQL);
            
            ps.setFloat(1, horaextra); 
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Dados Inseridos");
            
            pag.calcImpostos(cpfLabel.getText());
             try {
                    ps.close();
                    conn.close();
                    Thread.sleep(500);
                }
                catch(Exception e) { }
        }catch(SQLException e){
            System.out.println("Error no sql "+e);
        } 
 
             
               
    }//GEN-LAST:event_btnHoraExtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adicionais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adicionais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComissao;
    private javax.swing.JButton btnHoraExtra;
    private javax.swing.JButton btnInsalubridade;
    private javax.swing.JButton btnPericulosidade;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField txtComissao;
    private javax.swing.JTextField txtHoraExtra;
    private javax.swing.JTextField txtInsalubridade;
    private javax.swing.JTextField txtPericulosidade;
    // End of variables declaration//GEN-END:variables

    private boolean isNullOrEmpty(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
