/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.sql.PooledConnection;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.pool.OracleConnectionPoolDataSource;
import view.Principal.FuncionariobyCPF;
import view.Principal.PagamentobyCPF;


/**
 *
 * @author jonas
 */

public class pagamento extends javax.swing.JFrame {

    /**
     * Creates new form pagamento
     */
    public pagamento() {

        initComponents();
    }
    Principal pag = new Principal();
    public pagamento(String CPF) throws SQLException{
        pag.calcImpostos(CPF);
        //this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
    
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        
        cpfLabel.setText(CPF);
        
        OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
        ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
        ds.setUser("folhapagamento");
        ds.setPassword("senha");
        PooledConnection pc = ds.getPooledConnection();
        Connection conn=pc.getConnection();
        
        Principal.FuncionariobyCPF f = pag.new FuncionariobyCPF();
        Principal.PagamentobyCPF f2 = pag.new PagamentobyCPF();
        ResultSet rs = null, rs2 = null;
        String nome = "Nome_F";
        
        rs = f.find(CPF,conn);
        rs2 = f2.find(CPF, conn);
        try{
            if(rs.next()){
                nomeLabel.setText(rs.getString(nome));
            }
            if(rs2.next()){
                inssLabel.setText(rs2.getString("INSS_P"));
                fgtsLabel.setText(rs2.getString("FGTS_P"));
                if(rs2.getString("inssAux") == null || "0".equals(rs2.getString("inssAux"))){
                    inssAux.setText("");
                }else{
                    inssAux.setText("Inss já foi pago esse mês");
                }
                if(rs2.getString("fgtsAux") == null || "0".equals(rs2.getString("fgtsAux"))){
                    fgtsAux.setText("");
                }else{
                    fgtsAux.setText("Fgts já foi pago esse mês");
                }
                
            }
            /*
            resultSetClose(rs);
            resultSetClose(rs2);
            */
            try {
                    
                    conn.close();
                    Thread.sleep(500);
                }
                catch(Exception e) { }
        }catch(Exception ex){
        }
        
        //this.setSize(xsize, ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inssLabel = new javax.swing.JLabel();
        fgtsLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fgtsAux = new javax.swing.JLabel();
        inssAux = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CPF:");

        cpfLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpfLabel.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        nomeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeLabel.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("INSS:");

        inssLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inssLabel.setText("jLabel2");

        fgtsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fgtsLabel.setText("jLabel2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("FGTS:");

        jButton1.setText("Pagar INSS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pagar FGTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        fgtsAux.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fgtsAux.setText("jLabel5");

        inssAux.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inssAux.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fgtsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(inssLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inssAux, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fgtsAux, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inssLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(inssAux, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fgtsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(fgtsAux, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ResultSet rs = null;
        OraclePreparedStatement ps = null;

        
        Principal.PagamentobyCPF f2 = pag.new PagamentobyCPF();
        try{
            OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
            ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ds.setUser("folhapagamento");
            ds.setPassword("senha");
            PooledConnection pc = ds.getPooledConnection();
            Connection conn=pc.getConnection();
            
            rs = f2.find(cpfLabel.getText(), conn);
            
             try {
                    ps.close();
                    conn.close();
                    Thread.sleep(500);
             }
             catch(Exception e) { }
         }catch(SQLException e){
            System.out.println("Error no sql "+e);
         }
        
        
        try{
            if(rs.next()){
                if(rs.getString("inssAux") == null || "0".equals(rs.getString("inssAux"))){
                    String SQL = "UPDATE pagamento SET inssAux = ? where FK_PK_CPF_F ='" + cpfLabel.getText() + "'";
                    try{
                        OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
                        ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
                        ds.setUser("folhapagamento");
                        ds.setPassword("senha");
                        PooledConnection pc = ds.getPooledConnection();
                        Connection conn=pc.getConnection();
                           
                           
                           
                        ps = (OraclePreparedStatement)conn.prepareStatement(SQL);
                        ps.setFloat(1,1);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"INSS pago com Sucesso! ");
                        inssAux.setText("Inss já foi pago esse mês");
                        try {
                            ps.close();
                            conn.close();
                            Thread.sleep(500);
                        }
                        catch(Exception e) { }
                    }catch(SQLException e){
                        System.out.println("Error no sql "+e);
                    } 
                }else{
                    JOptionPane.showMessageDialog(null,"ERRO: INSS já foi pago esse mês ");
                }
            }
        }catch(Exception ex){
        }
        
        
    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               // TODO add your handling code here:
        
        ResultSet rs = null;
        OraclePreparedStatement ps = null;

        
        Principal.PagamentobyCPF f2 = pag.new PagamentobyCPF();
        try{
            OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
            ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
            ds.setUser("folhapagamento");
            ds.setPassword("senha");
            PooledConnection pc = ds.getPooledConnection();
            Connection conn=pc.getConnection();
            
            rs = f2.find(cpfLabel.getText(), conn);
            
             try {
                    ps.close();
                    conn.close();
                    Thread.sleep(500);
             }
             catch(Exception e) { }
         }catch(SQLException e){
            System.out.println("Error no sql "+e);
         }
        
        
        try{
            if(rs.next()){
                if(rs.getString("fgtsAux") == null || "0".equals(rs.getString("fgtsAux"))){
                    String SQL = "UPDATE pagamento SET fgtsAux = ? where FK_PK_CPF_F ='" + cpfLabel.getText() + "'";
                    try{
                        OracleConnectionPoolDataSource ds = new OracleConnectionPoolDataSource();
                        ds.setURL("jdbc:oracle:thin:@localhost:1521:xe");
                        ds.setUser("folhapagamento");
                        ds.setPassword("senha");
                        PooledConnection pc = ds.getPooledConnection();
                        Connection conn=pc.getConnection();
                           
                           
                           
                        ps = (OraclePreparedStatement)conn.prepareStatement(SQL);
                        ps.setFloat(1,1);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null,"FGTS pago com Sucesso! ");
                        fgtsAux.setText("Fgts já foi pago esse mês");
                        try {
                            ps.close();
                            conn.close();
                            Thread.sleep(500);
                        }
                        catch(Exception e) { }
                    }catch(SQLException e){
                        System.out.println("Error no sql "+e);
                    } 
                }else{
                    JOptionPane.showMessageDialog(null,"ERRO: FGTS já foi pago esse mês ");
                }
            }
        }catch(Exception ex){
        }
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel fgtsAux;
    private javax.swing.JLabel fgtsLabel;
    private javax.swing.JLabel inssAux;
    private javax.swing.JLabel inssLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nomeLabel;
    // End of variables declaration//GEN-END:variables
}
